GROQ_API_KEY = "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"
OPENROUTER_API_KEY = "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"
GEMINI_API_KEY = "AIzaSyBg__2jyKJk_22xAhJil1aGdUvdHTX_Uf0"